### ISSUE TITLE
handle router that routes between VLANs on the same trunk port

### ISSUE THREAD

**Issue by anarkiwi** [IQTLabs/poseidon#1316]
If a router is connected to a switch trunk port, it can route between VLANs on the same port.

For example, the router might receive a packet on VLAN a, then send the packet back to the same port in VLAN b, with the same L3 src/dst, but the router's own MAC src.

**Comment by cglewis** [comment]
Couldn't you specify a trunk port and MAC of the router for Poseidon to ignore using the trunk_ports config option to accomplish this? https://github.com/CyberReboot/poseidon/blob/master/installers/debian/templates#L43

**Comment by anarkiwi** [comment]
Definitely yes, just wondering if it would be valuable to automatically detect a port with routing (ie. same L3 src/dst pair seen in different VLANs on same port).

**Comment by cglewis** [comment]
ah, yes. automatic detection would be even better.
